# Generated by Django 5.0.4 on 2026-05-12 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('EXIT', 'Saída'), ('SUSPENSION', 'Suspensão'), ('REENTRY', 'Reentrada')], max_length=15, verbose_name='Motivo')),
                ('entry_date', models.DateField(verbose_name='Data de Entrada do Período')),
                ('exit_date', models.DateField(blank=True, null=True, verbose_name='Data de Saída do Período')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='members.member', verbose_name='Membro')),
            ],
            options={
                'verbose_name': 'Histórico',
                'verbose_name_plural': 'Históricos',
                'ordering': ['-entry_date'],
            },
        ),
    ]
