# Generated by Django 5.0.4 on 2026-05-19 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='approved_by',
        ),
        migrations.AddField(
            model_name='certificate',
            name='signed_at_director',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Diretor assinou em'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='signed_at_orientador',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Orientadora assinou em'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='signed_at_president',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Presidente assinou em'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='signed_by_director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director_signatures', to=settings.AUTH_USER_MODEL, verbose_name='Assinado pelo Diretor de Projetos'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='signed_by_orientador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orientador_signatures', to=settings.AUTH_USER_MODEL, verbose_name='Assinado pela Orientadora'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='signed_by_president',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='president_signatures', to=settings.AUTH_USER_MODEL, verbose_name='Assinado pelo Presidente'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='auth_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Hash de Autenticidade'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('PARTIAL', 'Assinado Parcialmente'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado')], default='PENDING', max_length=10, verbose_name='Status'),
        ),
    ]
