# Generated by Django 5.0.4 on 2026-05-19 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_remove_certificate_approved_at_and_more'),
        ('members', '0004_member_course_member_cpf_member_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='auth_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Hash de Autenticidade Global'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='description',
            field=models.TextField(verbose_name='Descrição/Conteúdo do Certificado'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Está Totalmente Válido?'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Emissão Oficial'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='members.member', verbose_name='Membro Colaborador'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', verbose_name='Motivo da Rejeição'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='signed_at_director',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora Assinatura (RH)'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='signed_at_orientador',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora Assinatura (Coordenação)'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='signed_at_president',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora Assinatura (Presidência)'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='signed_by_director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_certificates_director', to=settings.AUTH_USER_MODEL, verbose_name='Assinado por (RH)'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='signed_by_orientador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_certificates_orientador', to=settings.AUTH_USER_MODEL, verbose_name='Assinado por (Coordenação)'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='signed_by_president',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_certificates_president', to=settings.AUTH_USER_MODEL, verbose_name='Assinado por (Presidência)'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('PARTIAL', 'Assinado Parcialmente'), ('APPROVED', 'Aprovado e Emitido'), ('REJECTED', 'Rejeitado')], default='PENDING', max_length=15, verbose_name='Status do Fluxo'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
