# Generated by Django 5.0.4 on 2026-05-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('director', 'Recursos Humanos - RH'), ('president', 'Presidente'), ('orientador', 'Coordenador(a)')], default='director', max_length=15, verbose_name='Nível de acesso'),
        ),
    ]
