# Generated by Django 5.0.4 on 2026-06-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='certificate_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID do Certificado'),
        ),
    ]
