# Generated by Django 5.0.4 on 2026-06-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_course_member_cpf_member_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='suspension_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo da Suspensão'),
        ),
    ]
