# Generated by Django 5.0.4 on 2026-06-21 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_member_suspension_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descrição/Motivo da Punição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Aplicada em')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to='members.member', verbose_name='Membro')),
            ],
            options={
                'verbose_name': 'Punição',
                'verbose_name_plural': 'Punições',
                'ordering': ['-created_at'],
            },
        ),
    ]
